### ISSUE TITLE
Clojure 1.7.0 clojure.lang.ArityException

### ISSUE THREAD

**Issue by merqlove** [Engelberg/instaparse#112]
OS X 10.9
Java 1.8
Clojure 1.7.0
Instaparse 1.4.1

Simple project down with exception

```clojure
(ns hello-world.core
  (:use compojure.core ring.adapter.jetty)
  (:require [compojure.route :as route])
  (:gen-class))

(defroutes myapp
  (GET "/" [] "Hello World")
  (GET "/hello" [] "Fuck you up!")

  (route/not-found "Page not found")
)

(defn -main []
  (let [port "8080"]
    (run-jetty myapp {:port port})
    (println (str "Listening on port " port))))
```
```
clojure.lang.ArityException: Wrong number of args (2) passed to: StringReader
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:36)
	at instaparse.cfg$fn__831$safe_read_string__832.invoke(cfg.clj:163)
	at instaparse.cfg$process_string.invoke(cfg.clj:180)
	at instaparse.cfg$build_rule.invoke(cfg.clj:217)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at instaparse.cfg$build_rule.invoke(cfg.clj:215)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at instaparse.cfg$build_rule.invoke(cfg.clj:211)
	at instaparse.cfg$build_rule.invoke(cfg.clj:214)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
...
```
```
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
```
```
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(core.clj:1:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3628)
	at clojure.lang.Compiler.compile1(Compiler.java:7323)
	at clojure.lang.Compiler.compile1(Compiler.java:7313)
	at clojure.lang.Compiler.compile(Compiler.java:7390)
	at clojure.lang.RT.compile(RT.java:399)
	at clojure.lang.RT.load(RT.java:444)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$compile$fn__5453.invoke(core.clj:5877)
	at clojure.core$compile.invoke(core.clj:5876)
	at user$eval9$fn__18.invoke(form-init5523517331237543280.clj:1)
	at user$eval9.invoke(form-init5523517331237543280.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
```

**Comment by Engelberg** [comment]
Clojure 1.7.0 broke compatibility with earlier versions of Clojure in the arity of its StringReader.  Instaparse 1.4.1 addressed this, which makes me wonder if maybe you have another library in your dependencies that is indirectly including an older version of instaparse.  Can you check this?

**Comment by merqlove** [comment]
Hello @Engelberg, i have this in my project file. I need to check in ~/.m2 also?

```clojure
(defproject hello-world "0.1.0"
  :description "Compojure hello world web app"
  :url "https://github.com/cnsa/docker-compojure-hello-world"
  :min-lein-version "2.0.0"

  :plugins [[com.jakemccrary/lein-test-refresh "0.11.0"] ]

  :dependencies [[org.clojure/clojure "1.7.0"]
                 [instaparse "1.4.1" :exclusions [org.clojure/clojure]]
                 [org.clojure/data.json "0.2.6"]
                 [org.clojure/data.zip "0.1.1"]
                 [ring-mock "0.1.5"]
                 [compojure "1.4.0"]
                 [ring "1.2.1"]
                 [cheshire "5.5.0"]
                 [environ "1.0.1"]]
  :main hello-world.core
  :aot [hello-world.core])
```

**Comment by merqlove** [comment]
Tree also here:

```clojure
[cheshire "5.5.0"]
    [com.fasterxml.jackson.core/jackson-core "2.5.3"]
    [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
    [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
    [tigris "0.1.1"]
[clojure-complete "0.2.3" :exclusions [[org.clojure/clojure]]]
[com.novemberain/monger "3.0.1"]
    [clojurewerkz/support "1.1.0"]
        [com.google.guava/guava "18.0"]
    [org.mongodb/mongodb-driver "3.0.4"]
        [org.mongodb/bson "3.0.4"]
        [org.mongodb/mongodb-driver-core "3.0.4"]
[compojure "1.4.0"]
    [clout "2.1.2"]
    [medley "0.6.0"]
    [org.clojure/tools.macro "0.1.5"]
    [ring/ring-core "1.4.0"]
        [clj-time "0.9.0"]
            [joda-time "2.6"]
        [commons-fileupload "1.3.1"]
        [commons-io "2.4"]
        [crypto-equality "1.0.0"]
        [crypto-random "1.2.0"]
        [org.clojure/tools.reader "0.9.1"]
[environ "1.0.1"]
[hiccup "1.0.5"]
[instaparse "1.4.1" :exclusions [[org.clojure/clojure]]]
[org.clojure/clojure "1.6.0"]
[org.clojure/data.json "0.2.6"]
[org.clojure/data.zip "0.1.1"]
[org.clojure/tools.nrepl "0.2.10" :exclusions [[org.clojure/clojure]]]
[ring-mock "0.1.5"]
    [ring/ring-codec "1.0.0"]
        [commons-codec "1.6"]
[ring "1.2.1"]
    [ring/ring-devel "1.2.1"]
        [clj-stacktrace "0.2.5"]
        [ns-tracker "0.2.1"]
            [org.clojure/java.classpath "0.2.0"]
            [org.clojure/tools.namespace "0.1.3"]
    [ring/ring-jetty-adapter "1.2.1"]
        [org.eclipse.jetty/jetty-server "7.6.8.v20121106"]
            [org.eclipse.jetty.orbit/javax.servlet "2.5.0.v201103041518"]
            [org.eclipse.jetty/jetty-continuation "7.6.8.v20121106"]
            [org.eclipse.jetty/jetty-http "7.6.8.v20121106"]
                [org.eclipse.jetty/jetty-io "7.6.8.v20121106"]
                    [org.eclipse.jetty/jetty-util "7.6.8.v20121106"]
    [ring/ring-servlet "1.2.1"]
mini:app mrcr$ lein deps-tree
[cheshire "5.5.0"]
    [com.fasterxml.jackson.core/jackson-core "2.5.3"]
    [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.5.3"]
    [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.5.3"]
    [tigris "0.1.1"]
[clojure-complete "0.2.3" :exclusions [[org.clojure/clojure]]]
[com.novemberain/monger "3.0.1"]
    [clojurewerkz/support "1.1.0"]
        [com.google.guava/guava "18.0"]
    [org.mongodb/mongodb-driver "3.0.4"]
        [org.mongodb/bson "3.0.4"]
        [org.mongodb/mongodb-driver-core "3.0.4"]
[compojure "1.4.0"]
    [clout "2.1.2"]
    [medley "0.6.0"]
    [org.clojure/tools.macro "0.1.5"]
    [ring/ring-core "1.4.0"]
        [clj-time "0.9.0"]
            [joda-time "2.6"]
        [commons-fileupload "1.3.1"]
        [commons-io "2.4"]
        [crypto-equality "1.0.0"]
        [crypto-random "1.2.0"]
        [org.clojure/tools.reader "0.9.1"]
[environ "1.0.1"]
[hiccup "1.0.5"]
[instaparse "1.4.1" :exclusions [[org.clojure/clojure]]]
[org.clojure/clojure "1.7.0"]
[org.clojure/data.json "0.2.6"]
[org.clojure/data.zip "0.1.1"]
[org.clojure/tools.nrepl "0.2.10" :exclusions [[org.clojure/clojure]]]
[ring-mock "0.1.5"]
    [ring/ring-codec "1.0.0"]
        [commons-codec "1.6"]
[ring "1.2.1"]
    [ring/ring-devel "1.2.1"]
        [clj-stacktrace "0.2.5"]
        [ns-tracker "0.2.1"]
            [org.clojure/java.classpath "0.2.0"]
            [org.clojure/tools.namespace "0.1.3"]
    [ring/ring-jetty-adapter "1.2.1"]
        [org.eclipse.jetty/jetty-server "7.6.8.v20121106"]
            [org.eclipse.jetty.orbit/javax.servlet "2.5.0.v201103041518"]
            [org.eclipse.jetty/jetty-continuation "7.6.8.v20121106"]
            [org.eclipse.jetty/jetty-http "7.6.8.v20121106"]
                [org.eclipse.jetty/jetty-io "7.6.8.v20121106"]
                    [org.eclipse.jetty/jetty-util "7.6.8.v20121106"]
    [ring/ring-servlet "1.2.1"]
```

**Comment by Engelberg** [comment]
A few questions/suggestions:
1. Why do you exclude clojure.org in the line where you include instaparse?
2. Try using the latest version of ring and let me know if that changes things. The latest version is 1.4.0
3. I've copied your minimal project onto my machine to try to duplicate your problem.  How are you running the server?  "lein run" or something else?

**Comment by Engelberg** [comment]
When I run your project (I omitted the exclusion on the instaparse lein, since I don't see why it is necessary), I get an error that Jetty is being invoked with a string rather than a number.  When I changed the port in -main from "8080" to just the number 8080, I ran it and everything seemed to work just fine.

Maybe you need to clean out your dependencies with lein clean?

**Comment by merqlove** [comment]
I found this exclusion as a tip on same fail.
Yeah, i’m starting demo with lein run.
I’m new to Clojure. After i did lein clean & changed port type for Number, all works fine.
Thanks in advance!

**Comment by Engelberg** [comment]
Glad to hear it is working for you now.
