### ISSUE TITLE
casting error

### ISSUE THREAD

**Issue by ChipNowacek** [Engelberg/instaparse#157]
I dumb as a stump. Any ideas what might cause this exception?

Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.Associative
	at clojure.lang.RT.assoc(RT.java:792)
	at clojure.core$assoc__4371.invokeStatic(core.clj:191)
	at clojure.core$assoc__4371.invoke(core.clj:190)
	at instaparse.reduction$apply_standard_reductions$iter__241__245$fn__246.invoke(reduction.clj:54)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$into.invokeStatic(core.clj:6610)
	at clojure.core$into.invoke(core.clj:6604)
	at instaparse.reduction$apply_standard_reductions.invokeStatic(reduction.clj:52)
	at instaparse.reduction$apply_standard_reductions.invoke(reduction.clj:48)
	at instaparse.cfg$build_parser_from_combinators.invokeStatic(cfg.clj:292)
	at instaparse.cfg$build_parser_from_combinators.invoke(cfg.clj:288)
	at instaparse.core$parser.invokeStatic(core.clj:248)
	at instaparse.core$parser.doInvoke(core.clj:171)
	at clojure.lang.RestFn.invoke(RestFn.java:486)
	at docopt.core$docopt.invokeStatic(core.clj:155)
	at docopt.core$docopt.invoke(core.clj:140)
	at docopt.core$docopt.invokeStatic(core.clj:150)
	at docopt.core$docopt.invoke(core.clj:140)

**Comment by Engelberg** [comment]
Can you give me a little more context, for example, what input you are using?

Offhand, this reminds me of an error I've seen when the map passed to insta/transform was problematic, such that a lower node in the tree was transformed into something incompatible with the transformation function of a higher node in the tree.  But I don't see insta/transform in your stack trace, so I don't know if that's it.  As a starting point, I'd recommend you test your uses of insta/transform thoroughly.

**Comment by ChipNowacek** [comment]
Being new, I'll try to test as you suggest. Using the developer's example, I was able to reproduce the error on [this branch](https://github.com/ChipNowacek/docopt.cluno/tree/try-to-get-github-example-to-work). If sharing it is inappropriate in some way, I apologize.

**Comment by carocad** [comment]
@Engelberg this is most likely an error on my side. I am the creator of `docopt.cluno` the project that @ChipNowacek is using and through which he got that stacktrace.

I dont think you need to care about it, I will discuss it with @ChipNowacek on my repo ;)
